# main text of home
title: 祢津 久
bio: フリーランスDXコンサルタント・生活習慣サポーター

# twitter summary info
description: 一人ひとりに寄り添うデジタルと健康のトータル支援

# if it's an external image, update below for true
external-image: false
picture: assets/images/myphoto.jpg

# your site color theme, true for dark theme, false to light theme, auto to switch with system.
dark-theme: auto

# If you want to include your resume, set to true and specify source
resume: true
resume-external: true
resume-url: https://google.com/?q=my+resume

# your GitHub Pages URL
url: https://hisashi53.github.io/indigo

permalink: /:title/

# Google Analytics (optional)
# analytics-google: 'UA-XXXXXXX'

# Disqus comments settings
disqus:
  shortname: github
  categories: [blog, project]

# Social accounts
facebook: yourfacebook
twitter: yourtwitter
instagram: yourinstagram
linkedin: yourlinkedin
github: hisashi53
email: your.email@example.com

# Author profiles
authors:
  hisashi:
    name: 祢津 久
    bio: DXと生活改善の両面から寄り添うパートナー
    external-image: false
    picture: assets/images/myphoto.jpg
    twitter: yourtwitterhandle

# Site layout
width: normal
projects: true
about: true
blog: true
read-time: true
show-tags: true
related: true
post-advance-links: [blog]
show-author: true
animation: true

# Default values for posts
defaults:
  - scope:
      path: ""
      layout: "post"
    values:
      hidden: false

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Compress settings
compress_html:
  ignore:
    envs:
      - development
      - stage

# Excluded files from build
exclude:
  [
    "README.md",
    "Gemfile",
    "Gemfile.lock",
    "FAQ.md",
    "vendor",
  ]
